### ISSUE TITLE
v2 Voice SIP domains/endpoints

### ISSUE THREAD

**Issue by ecwyne** [Bandwidth/bandwidth.github.io#243]
Looks like there's a lot happening with moving everything over to v2. I'm wondering if anyone can point me in the right direction to set up SIP domains and endpoints with v2. I have not been able to find any documentation for this. Thank you!

**Comment by ecwyne** [comment]
@dtolbert-bw @jmulford-bw @Aubron

**Comment by ghost** [comment]
@ecwyne apologies for the delay! v2 voice doesn't support SIP Domains & Endpoints today. We're working towards that functionality, and will keep ya up to date. Can you reach out to support.bandwidth.com and open a ticket there and we'll be sure to add you to the list.

In the meantime v1 still supports domains & endpoints but we're not actively adding new customers to that service.

Cheers!
